### 200 OK
GET http://localhost:5000/offers HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJNb2RlcmF0b3IiLCJ1c2VySWQiOjU1LCJyb2xlIjoibW9kZXJhdG9yIiwibGFzdE5hbWUiOiJNb2RlcmF0b3JvdnljaCIsImF2YXRhciI6ImFub24ucG5nIiwiZGlzcGxheU5hbWUiOiJtb2RlcmF0b3JkbiIsImJhbGFuY2UiOiIwIiwiZW1haWwiOiJtb2RlcmF0b3JAZ21haWwuY29tIiwicmF0aW5nIjowLCJpYXQiOjE3NDI5MzI3MDcsImV4cCI6MTc0MjkzNjMwN30.SUzQcJgqBhcJjcEmZwWYV2RKq0qDxfzbKnqv9wHO7JQ

### 200 OK
GET http://localhost:5000/offers?page=2&results=2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJNb2RlcmF0b3IiLCJ1c2VySWQiOjU1LCJyb2xlIjoibW9kZXJhdG9yIiwibGFzdE5hbWUiOiJNb2RlcmF0b3JvdnljaCIsImF2YXRhciI6ImFub24ucG5nIiwiZGlzcGxheU5hbWUiOiJtb2RlcmF0b3JkbiIsImJhbGFuY2UiOiIwIiwiZW1haWwiOiJtb2RlcmF0b3JAZ21haWwuY29tIiwicmF0aW5nIjowLCJpYXQiOjE3NDI5MzI3MDcsImV4cCI6MTc0MjkzNjMwN30.SUzQcJgqBhcJjcEmZwWYV2RKq0qDxfzbKnqv9wHO7JQ

### 423 'this page only for moderator' 
GET http://localhost:5000/offers HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJDcmVhdGl2ZSIsInVzZXJJZCI6NTQsInJvbGUiOiJjcmVhdG9yIiwibGFzdE5hbWUiOiJDcmVhdG92eWNoIiwiYXZhdGFyIjoiYW5vbi5wbmciLCJkaXNwbGF5TmFtZSI6ImNyZWF0aXZlZG4iLCJiYWxhbmNlIjoiMCIsImVtYWlsIjoiY3JlYXRpdmVAZ21haWwuY29tIiwicmF0aW5nIjowLCJpYXQiOjE3NDI5MzM0NzEsImV4cCI6MTc0MjkzNzA3MX0.NtOrcDh-Yg5vw9GcRZam6Oh8ohPuQNF70Sn06Fsfpo8
